data:
  datapath: '/project/MLFluids/NS_Re500_s256_T100_test_cartesian.npy'
  Re: 500
  total_num: 100
  offset: 0
  n_sample: 20
  time_interval: 0.5
  nx: 256
  nt: 128
  sub: 4
  sub_t: 1
  shuffle: False

model:
  layers: [64, 64, 64, 64, 64]
  modes1: [8, 8, 8, 8]
  modes2: [8, 8, 8, 8]
  modes3: [8, 8, 8, 8]
  fc_dim: 128

test:
  batchsize: 2
  ckpt: '/home/cfos3120/checkpoints/cartesian_testing/PINO-pretrain-Re500-05s-4C0_sens8.pt'
  pde_loss_factor: 'self_scaled'
  
others:
  project: 'PINO-None'
  group: 'eval'


